artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url:
    - https://datasetsurl.onrender.com/training
    - https://datasetsurl.onrender.com/description
    - https://datasetsurl.onrender.com/diets
    - https://datasetsurl.onrender.com/medications
    - https://datasetsurl.onrender.com/precautions
    - https://datasetsurl.onrender.com/workout_df
  

data_transformation:
  root_dir: artifacts/data_transformation
  symptoms_list_path: artifacts/symptoms_list

model_training:
  model_dir: artifacts/model
  train_data_path: artifacts/data_transformation/train.csv
  model_name: model.joblib
  disease_list_path: artifacts/disease_list
  encoder_path: artifacts/model/encoder.joblib

model_evaluation:
  model_evaluation_dir: artifacts/model_evaluation
  model_path: artifacts/model/model.joblib
  test_data_path: artifacts/data_transformation/test.csv
  metric_file_path: artifacts/model_evaluation/metrics.json
  encoder_path: artifacts/model/encoder.joblib
